from .feature_low_rank_inner import FeatureLowRankInnerRegressor
from .feature_low_rank_inner import FeatureLowRankInnerClassifier
from .feature_low_rank_dist import FeatureLowRankDistanceRegressor
from .feature_low_rank_dist import FeatureLowRankDistanceClassifier
